stages:
  - build
  - test

.common-rules:
  - &rule-is-mr
    if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - &rule-is-main
    if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - &rule-is-tag
    if: $CI_COMMIT_TAG

.setup:
  image: fabernovel/android:api-35-ndk-v1.10.1
  cache:
    key:
      files:
        - android/build.gradle
        - package-lock.json
    paths:
     - .gradle/wrapper
     - .gradle/caches
      - node_modules/
  before_script:
    - apt update -y && apt install -y curl ca-certificates gnupg
    - mkdir -p /etc/apt/keyrings
    - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
    - apt update -y && apt install -y nodejs
    - node --version
    - npm install

.android_setup:
  extends: .setup
  before_script:
    - !reference [.setup, before_script]
    - cd android/
    - bundle install
    - wget https://gitlab.com/gitlab-org/cli/-/releases/v1.74.0/downloads/glab_1.74.0_linux_amd64.deb
    - apt install -y ./glab_1.74.0_linux_amd64.deb
    - glab auth login --hostname $CI_SERVER_FQDN --job-token $CI_JOB_TOKEN
    - glab securefile download --all --output-dir app/.secure_files/
    - export GRADLE_USER_HOME=`pwd`/.gradle

test:android:
  extends: .android_setup
  stage: test
  script:
    - bundle exec fastlane test

test:ios:
  stage: test
  script:
    - echo "This is a placeholder job."
    - echo "Running iOS tests..."

build:android:debug:
  extends: .android_setup
  stage: build
  rules:
    - <<: *rule-is-main
      when: never
    - *rule-is-mr
  script:
    - bundle exec fastlane android ci_build_release_debug

build:android:release:
  extends: .android_setup
  stage: build
  rules:
    - <<: *rule-is-mr
      when: never
    - *rule-is-main
  artifacts:
    paths:
      - android/app/build/outputs/
  script:
    - bundle exec fastlane android ci_build_release_release

draft:android:release:
  extends: .android_setup
  stage: build
  rules:
    - <<: *rule-is-mr
      when: never
    - <<: *rule-is-main
      when: never
    - *rule-is-main
  needs:
    - job: build:android:release
      artifacts: true
  script:
    - bundle exec ci_release.rb

build:ios:
  stage: build
  script:
    - echo "This is a placeholder job."
    - echo "Build iOS artifacts..."