test:
  image: fabernovel/android:api-33-v1.7.0
  stage: test
  script:
    - cd android/
    - bundle install
    - bundle exec fastlane test

build:
  image: fabernovel/android:api-33-v1.7.0
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - android/vendor/bundle
  script:
    - apt update -y && apt install -y curl nodejs npm
    - npm install
    - cd android/
    - bundle install
    - apt update -y && apt install -y curl
    - wget https://gitlab.com/gitlab-org/cli/-/releases/v1.74.0/downloads/glab_1.74.0_linux_amd64.deb
    - apt install ./glab_1.74.0_linux_amd64.deb
    - glab auth login --hostname $CI_SERVER_FQDN --job-token $CI_JOB_TOKEN
    - glab securefile download --all --output-dir .secure_files/
    - bundle exec fastlane build
