# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Create and sign a new build (local)"
  lane :clean_build_release do
    gradle(tasks: ["clean", "assembleRelease", "bundleRelease"])
  end

  desc "Create and sign a CI build"
  lane :ci_build_release do
    gradle(tasks: ["assembleRelease", "bundleRelease"])
  end

  desc "Submit a new Beta build to the Google Play store"
  lane :beta do
    versions = google_play_track_version_codes(track: "internal")
    version_code = versions[0]

    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      release_status: 'draft',
      version_code: version_code + 1,
    )
  end
end
